Repository nimblehq/our-team, pull requests merged in 2019-04, with the labels that each got.

#38 Updating some of our tools and projects
  README.md
Labels: priority : normal, type : chore

#39 Chore/update early 2019
  README.md
Labels: priority : normal, type : chore

#40 Update vacancies URLs
  join-us/openings/internship-software-developer.md
  join-us/openings/lead-android-developer.md
  join-us/openings/lead-ios-developer.md
  join-us/openings/lead-web-developer.md
  join-us/openings/ruby-rails-developer-bangkok.md
  join-us/openings/ruby-rails-developer-danang.md
  join-us/openings/technical-product-owner.md
  join-us/openings/web-developer.md
  join-us/our-recruitment-process.md
Labels: priority : high, type : chore

#41 Update listing of vacancies
  join-us/openings/internship-software-developer.md
  join-us/openings/talent-manager.md
  join-us/our-recruitment-process.md
Labels: priority : high, type : feature

#42 Document challenge process for the Talent Manager role
  join-us/our-recruitment-process.md
Labels: priority : normal, type : feature
